services:

  #  start Postgres, and ensure that data is stored to a mounted volume
  postgres:
    image: 'postgres:latest'
    container_name: postgres_db
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vishal
      POSTGRES_DB: view_count
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: